### ISSUE TITLE
Only fixed length for longformer

### ISSUE THREAD

**Issue by demdecuong** [allenai/longformer#102]
Hi, I am a begineer.
I wonder that does longformer just support for fixed length since the computations for attention is divided into chunk due to
`assert seqlen % (w * 2) == 0 `
Does my opinion is right ? 
So every input document we must padding it to a fixed length right ?

**Comment by ibeltagy** [comment]
You need to pad the input to the nearest `w*2` seqlen. Check the readme example for a helper function that does that padding. The HF code will do the padding for you.
