### ISSUE TITLE
Further Pretraining on in-domain corpus

### ISSUE THREAD

**Issue by baradl** [allenai/longformer#104]
Hello everybody, 

I'm interested in continued pretraining of the longformer on in-domain text. I'm using the `pretrain_and_evaluate` method from this [notebook](https://github.com/allenai/longformer/blob/master/scripts/convert_model_to_long.ipynb) on the longformer base model. 
It leads to large ram consumption as it increasingly takes up more and more until it reaches the hardware limits - 32GB wasn't enough. The corpus is not large, just a few hundred MB. I experience the same behaviour with the script provided by the transformer library `run_language_modeling.py` but with a slower increase in ram consumption. 

Any ideas why I might experience this behaviour or suggestions on how to solve it?

Cheers

**Comment by ibeltagy** [comment]
I haven't used `run_language_modeling.py` that much so I am not sure. I would suggest you ask in the HF/transformers repo as this is a general issue about their trainer.

**Comment by baradl** [comment]
Thanks for the reply. In case someone is interested, [7065](https://github.com/huggingface/transformers/issues/7065) in the transformer deals now with this issue. It's not clear whether it'll be fruitful
