### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by Yangxiaojun1230** [allenai/longformer#105]
When I train on a classification model by Longformer
def forward(self,input):
embding=input['enc']
att_mask=input['mask']
att_mask[:,[100,300,500,800,1200,]]=2
labels=input['targets']
print('jeff:',embding.device,att_mask.device,self.l1.device,embding.shape,att_mask.shape,self.maxlen)

    logit=self.l1(inputs_embeds=embding,attention_mask=att_mask)#[:2]
    return [logit,labels]
Meet error:
pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [205,0,0], thread: [95,0,0] Assertion srcIndex < srcSelectDimSize failed

max_num_extra_indices_per_batch = num_extra_indices_per_batch.max()
RuntimeError: cuda runtime error (710) : device-side assert triggered at /pytorch/aten/src/THC/THCReduceAll.cuh:327

I checked the length of the attention_mask is same as the config.max_len which is like [bs,max_len]
Do anyone meet the same issue?

**Comment by ibeltagy** [comment]
Can you run your code again with CUDA_LAUNCH_BLOCKING=1 to get a more accurate error message and post the full stack trace? Also, it is helpful if you can post a short snippet that reproduces your error.

**Comment by Yangxiaojun1230** [comment]
> Can you run your code again with CUDA_LAUNCH_BLOCKING=1 to get a more accurate error message and post the full stack trace? Also, it is helpful if you can post a short snippet that reproduces your error.

Thank you for your reply.
I tried CUDA_LAUNCH_BLOCKING=1 python pl_Class.py . Almost the same message.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [205,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
**But the location is different:**
 "/home/yangjeff/anaconda3/lib/python3.6/site-packages/transformers/modeling_bert.py", line 178, in forward
  embeddings = inputs_embeds + position_embeddings + token_type_embeddings
RuntimeError: CUDA error: device-side assert triggered

And when access to the attention_mask, I got a error,it seems attention_mask become inf. I am sure before input into the model,it could be accessed.
        if attention_mask is not None:
            print('j1:',attention_mask.shape)

            attention_mask = attention_mask.squeeze(dim=2).squeeze(dim=1)
            print('x11:',attention_mask[0][:3])
            key_padding_mask = attention_mask < 0
            extra_attention_mask = attention_mask > 0
            remove_from_windowed_attention_mask = attention_mask != 0
           num_extra_indices_per_batch = extra_attention_mask.long().sum(dim=1)
            max_num_extra_indices_per_batch = num_extra_indices_per_batch.max()
nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: cuda runtime error (710) : device-side assert triggered at /pytorch/aten/src/THC/THCReduceAll.cuh:327

**Comment by ibeltagy** [comment]
There's something wrong with your input resulting in the tensors in this line 
```embeddings = inputs_embeds + position_embeddings + token_type_embeddings```
are not compatible and can't be added together. 
Try to put a breakpoint before that line, print the shapes of each tensor, and make sure they are what you would expect.

**Comment by Yangxiaojun1230** [comment]
Actuall I didn't changed this part code, the original is from class BertEmbeddings.forward()
        print('xxj:',inputs_embeds.shape,inputs_embeds.device,position_embeddings.shape,position_embeddings.device,token_type_embeddings.shape,token_type_embeddings.device)
        embeddings = inputs_embeds + position_embeddings + token_type_embeddings
        embeddings = self.LayerNorm(embeddings)
        embeddings = self.dropout(embeddings)
        return embeddings

xxj: torch.Size([1, 3072, 1176]) cuda:0 torch.Size([1, 3072, 1176]) cuda:0 torch.Size([1, 3072, 1176]) cuda:0
I set the bs=1,max-len=3072,inputs_embeds=[1176,]

Finally, I think I find the reason.
That's since at first I initial  RobertaModel.from_pretrained(model_path) and it  call class BertEmbeddings.forward()。 And then I initial LongformerForSequenceClassification(config=config) and it also call the calss BertEmbeddings.forward(). But the input size of two model is different.  Do you know how to initial two seperate model?

**Comment by Yangxiaojun1230** [comment]
I fixed finally
