### ISSUE TITLE
BERT to Long on TPUs via xla?

### ISSUE THREAD

**Issue by gorka96** [allenai/longformer#109]
Hi,

I would need to train a longformer model for Basque language, starting from the BERTeus (BERT for Basque) checkpoint.

For that purpose, we adapted your tutorial convert_model_to_long.ipynb for BERT(eus) instead of RoBERTa, following the instructions already available on these issues. However, we can't train it on our small GPUs (11GB) due to memory requirements. Thus, we are planing to train the model on TPUs. But it seems that TF or Pytorch-xla implementation would be needed.

I saw that until recently, pytorch-xla TPU support was just for finetuning on downstream tasks, but I understood that it wasn't enough for our needs. But the recent updates at #101 already make possible to train a longformer model on TPUs.

I wonder if this would also work for training a longformer model starting from a BERT checkpoint. I guess that it does, but what changes would we need to make to convert_model_to_long.ipynb so that it runs on TPUs?

Thanks,
Gorka

**Comment by ibeltagy** [comment]
RoBERTa and BERT are very similar so it should work. 

> changes to convert_model_to_long.ipynb

Nothing. You run `convert_model_to_long` once to create your model and save it to the disk, then you can load it from desk using `.from_pretrained` as any HF model.

**Comment by gorka96** [comment]
Thanks for the fast answer!
