### ISSUE TITLE
[Assertion `srcIndex < srcSelectDimSize` failed.] on BERT to Longformer.

### ISSUE THREAD

**Issue by gorka96** [allenai/longformer#110]
Hi,

I was training a Longformer model starting from a BERT checkpoint based on the code of convert_model_to_long.ipynb
and i got the next error while training (after some good 700 steps):

/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [221,0,0], thread: [63,0,0] __Assertion `srcIndex < srcSelectDimSize` failed__.

Iteration:   3%|████                                                                                                                                                | 726/26661 [26:33<15:48:31,  2.19s/it]
Epoch:   0%|                                                                                                                                                                         | 0/8 [26:33<?, ?it/s]

Traceback (most recent call last):
...
File "/mnt/datuak/virtualenvs/transformers/lib/python3.6/site-packages/transformers/modeling_longformer.py", line 299, in forward
    is_global_attn = any(is_index_global_attn.flatten())
RuntimeError: CUDA error: device-side assert triggered

with CUDA_LAUNCH_BLOCKING=1 activated:
...
  File "/mnt/datuak/virtualenvs/transformers/lib/python3.6/site-packages/transformers/modeling_bert.py", line 182, in forward
    __embeddings = inputs_embeds + position_embeddings + token_type_embeddings__
RuntimeError: CUDA error: device-side assert triggered

I'm training it on a single GPU (GeForce RTX 2080ti, 11GB) using a batch size of 1, gradient Accumulation steps = 64, and gradient-checkpointing=True so that it fits (doesn't take more than 7-8GB). The training starts correctly, until this error happens (always after 726 steps with this dataset).

linux: Ubuntu 18.04.4 LTS
python: 3.6
torch: 1.4.0
transformers: 3.0.2

I read on transformers/issues that "it’s definitely that you’ve got a bad index into the positional embeddings".

the solution they suggest is to reduce --block-size = 512 to block_size<511 (4096/<4095 in our case), but I guess that this can't be done, as our block size has to be multiple of 512 (BERT block size that we want to enlarge). 

[Updated0: I tried with block-size 3584, which is <4095, and multiple of 512, but i got the same error.]

So I need to solve the real problem under it for this, but I am lost.

any other hint?

Thanks,
Gorka

**Comment by gorka96** [comment]
I had already followed the instructions from #86 to adapt the script convert_model_to_long.ipynb for BERT models, but I missed the part from #95 where changes to embeddings positions are needed.

from:
`model.roberta.embeddings.position_embeddings.weight.data = new_pos_embed`
to:
` model.bert.embeddings.position_ids = torch.from_numpy(tf.range(new_pos_embed.shape[0], dtype=tf.int32).numpy()[tf.newaxis, :])
    model.bert.embeddings.position_embeddings = torch.nn.Embedding.from_pretrained(new_pos_embed)` 

With that change I get short of GPU memory(i even tried with max_pos of 1024), even if I expected it to fit in (with batch size 1 + gradient Accumulation and gradient-checkpointing). I will need to test it on a bigger GPU or a TPU before saying that these changes solve the CUDA error I had.

Regards,
Gorka

**Comment by ibeltagy** [comment]
Is this base or large? If this is base, with max_pos 1024, gradient-checkpointing, batch size 1, even a 12GB gpu should have enough memory.

**Comment by gorka96** [comment]
Its base.

**Comment by gorka96** [comment]
Hi again, 

I rewrote my code (starting from your script) to have a more comparable code with your script, and it seems that in the process I get rid of the issue i had there. The only memory problem that I have is while I load the training dataset:

`INFO:__main__:Pretraining bert-base-1024 ... 
INFO:filelock:Lock 139936463252616 acquired on wikitext-103-raw/cached_lm_BertTokenizerFast_1022_wiki.valid.raw.lock
INFO:transformers.data.datasets.language_modeling:Loading features from cached file wikitext-103-raw/cached_lm_BertTokenizerFast_1022_wiki.valid.raw [took 0.035 s]
INFO:filelock:Lock 139936463252616 released on wikitext-103-raw/cached_lm_BertTokenizerFast_1022_wiki.valid.raw.lock
INFO:__main__:Loading and tokenizing training data is usually slow: wikitext-103-raw/wiki.train.raw
INFO:filelock:Lock 139936463252448 acquired on wikitext-103-raw/cached_lm_BertTokenizerFast_1022_wiki.train.raw.lock
INFO:transformers.data.datasets.language_modeling:Creating features from dataset file at wikitext-103-raw` 

And then it crashes because It needs more RAM memory than what I got (12G), (which doesn't make much sense as the file is only 580MB).

so I took the first 100K lines of the file, and the training goes smoothly, with max_pos of 1024 and batch size of 1 or 2, it only uses 3-4GB of the GPU while training.

I only have one question left before closing this issue. I wonder if using `BertForMaskedLM & BertTokenizerFast` and `AutoModelWithLMHead & AutoTokenizer` are equivalent and freely interchangeable. They seem both to work correctly for me.

Regards,
Gorka

**Comment by ibeltagy** [comment]
Glad it is working.

> are equivalent and freely interchangeable. 
Yes, `BertForMaskedLM` and `AutoModelWithLMHead.from_pretraind(some_bert_model)`, and `BertTokenizerFast` and `AutoTokenizer.from_pretrained(some_bert_tokenizer, use_fast=True)` are equivalent thanks to HF/transformers magic.

**Comment by gorka96** [comment]
Thank you!
