### ISSUE TITLE
Compile tvm kernel in newer version of CUDA

### ISSUE THREAD

**Issue by elb3k** [allenai/longformer#176]
Hi appreciate the repo.

I was using longformer with cuda 11.0 (needed for newer gpus). But `lib_diagonaled_mm_float32_cuda.so` was compiled on cuda 10.0. 
Instructions to compile with tvm is fetching docker with cuda 10.0 image anyway, is there any way/hint to compile library using newer CUDA version. Or whole tvm library was compiled with cuda 10.0?

**Comment by jannessm** [comment]
maybe the implementation from huggingface helps: https://github.com/huggingface/transformers/blob/master/src/transformers/models/longformer/modeling_longformer.py
