### ISSUE TITLE
ImportError: cannot import name 'nvcc' from 'tvm.contrib' (unknown location)

### ISSUE THREAD

**Issue by sarvghotra** [allenai/longformer#24]
Hi there, I am trying to run the sample model code, point3 under "How to use", but I ran into following issue. 
ImportError: cannot import name 'nvcc' from 'tvm.contrib' (unknown location)

I thought the "Install environment and code" would cover all the dependencies. Please let me know if I am missing something.

Thanks in advance.

**Comment by sarvghotra** [comment]
Realized that I don't need to compile the kernal; For some path issue it was not loading the pre-compiled kernal correctly.

**Comment by safooray** [comment]
from tvm.contrib import nvcc
ImportError: cannot import name 'nvcc'

I get this when trying to compile the kernel from scratch. Did I miss something in the cmake config? I can import a lot of TVM modules but not nvcc.

My cuda version is: Cuda compilation tools, release 10.0, V10.0.130

**Comment by ibeltagy** [comment]
Let's discuss the nvcc thing in your other issue https://github.com/allenai/longformer/issues/52

**Comment by YJYJLee** [comment]
@sarvghotra how did you fix the path issue? What modifications do we need to load precompiled kernel correctly?

**Comment by wsmzzz** [comment]
@YJYJLee  Did you fix the path issue? How to  use longformer in 'tvm' mode  without compile the CUDA kernel
