### ISSUE TITLE
How much memory does longformer-base take? Always out of memory

### ISSUE THREAD

**Issue by wyin-Salesforce** [allenai/longformer#26]
I am using longformer-base, with batch_size 8, and --max_seq_length=1000
my GPU has  16130MiB, always out of memory....
is this normal? thanks

**Comment by ibeltagy** [comment]
is this the TriviaQA script? the TriviaQA script takes less than 6GB of memory for a 1024 sequence.
Notice that this script always uses batch_size=1 (check [here](https://github.com/allenai/longformer/blob/master/scripts/triviaqa.py#L243)), so if you are really using batch_size of 8, then yes, it should OOM.

**Comment by wyin-Salesforce** [comment]
Thanks for your reply. My code is basically glue script (pretty much like TriviaQA), I am training something like NLI. Maybe I should decrease batch size to 1 as well.

**Comment by ibeltagy** [comment]
Yes, batch_size=8 is a lot. I will also suggest trying the new implementation of the sliding window attention (https://github.com/allenai/longformer/pull/27) with fp16. It will save you some memory and it is faster.

**Comment by ibeltagy** [comment]
Closing. Please feel free to reopen or create a new one if you have more questions.
