### ISSUE TITLE
Question generation

### ISSUE THREAD

**Issue by timsuchanek** [allenai/longformer#30]
Given a text corpus, would it be possible to generate questions using **longformer**?

**Comment by ibeltagy** [comment]
Generation needs a model like BART or like GPT-2. Check answers here https://github.com/allenai/longformer/issues/28 and here https://github.com/allenai/longformer/issues/29

**Comment by ibeltagy** [comment]
I will close this issue for now. Please feel free to reopen if you have other questions.

**Comment by patil-suraj** [comment]
Hi @timsuchanek , check this [project](https://github.com/patil-suraj/question_generation) for question generation, it supports T5 and BART for now, I'll also add Lonformer when LonformerEncoderDecoder is ready.

**Comment by GOURAVSUMAN** [comment]
> Hi @timsuchanek , check this [project](https://github.com/patil-suraj/question_generation) for question generation, it supports T5 and BART for now, I'll also add Lonformer when LonformerEncoderDecoder is ready.

Which Bart model can be used

**Comment by GOURAVSUMAN** [comment]
> Hi @timsuchanek , check this [project](https://github.com/patil-suraj/question_generation) for question generation, it supports T5 and BART for now, I'll also add Lonformer when LonformerEncoderDecoder is ready.

I am not able to use BART model in this
