### ISSUE TITLE
triviaqa.py code issue

### ISSUE THREAD

**Issue by Akshayextreme** [allenai/longformer#31]
Encounter below issue when calling `main` function from [triviaqa.py](https://github.com/allenai/longformer/blob/master/scripts/triviaqa.py) script explicitly (through another script)

**Error log:**
NameError                                 Traceback (most recent call last)
<ipython-input-6-a072bfb76ccf> in <module>
----> 1 triviaqa.main(args)

/notebooks/files/longformer/triviaqa.py in main(args)
    658         torch.cuda.manual_seed_all(args.seed)
    659 
--> 660     model = TriviaQA(args)
    661 
    662     logger = TestTubeLogger(

/notebooks/files/longformer/triviaqa.py in __init__(self, args)
    260         self.tokenizer.max_len_single_sentence = self.args.max_seq_len
    261         self.tokenizer.max_len_sentences_pair = self.args.max_seq_len
--> 262         self.model = self.load_model()
    263         self.num_labels = 2
    264         self.qa_outputs = torch.nn.Linear(self.model.config.hidden_size, self.num_labels)

/notebooks/files/longformer/triviaqa.py in load_model(self)
    266 
    267     def load_model(self):
--> 268         model = Longformer.from_pretrained(args.model_path)
    269         for layer in model.encoder.layer:
    270             layer.attention.self.attention_mode = self.args.attention_mode

NameError: name 'args' is not defined

**Changes needed [here](https://github.com/allenai/longformer/blob/d574a10f0adb2d7649ec6449364ceaa60de3a395/scripts/triviaqa.py#L268):**
From:        `model = Longformer.from_pretrained(args.model_path)`
To:            `model = Longformer.from_pretrained(self.args.model_path)`

**Comment by ibeltagy** [comment]
Good catch. Fixed https://github.com/allenai/longformer/commit/671f6e056dd2a3f51ac5843f8810f5ff68d5c85b
