### ISSUE TITLE
installation requires old version of torch (1.2)

### ISSUE THREAD

**Issue by aviularu** [allenai/longformer#32]
Can you support also the newest torch and transformers libraries?

**Comment by leslyarun** [comment]
Yes, we need support for the latest version of torch and transformers libraries @ibeltagy

**Comment by ibeltagy** [comment]
There's a PR for it. We will fix this soon.

**Comment by ibeltagy** [comment]
Fixed in the latest release https://github.com/allenai/longformer/releases/tag/v0.2
