### ISSUE TITLE
Problem running on Colab anyone?

### ISSUE THREAD

**Issue by pchankh** [allenai/longformer#35]
I am having issues running longformer in colab.
Can someone advise the installation approach?

I tried.
!pip install git+https://github.com/allenai/longformer.git --user
!pip install pytorch_lightning

cannot seems to get import longformer to work.

**Comment by pchankh** [comment]
Resolved this by 

!pip install torch==1.2.0

**Comment by ibeltagy** [comment]
Closing. Please feel free to reopen or create a new one if you have more questions.
