### ISSUE TITLE
Transformers Longformer version and difference with current release

### ISSUE THREAD

**Issue by pchankh** [allenai/longformer#39]
Is there any difference between the version released by transformers team 2.9.1 ?
thanks.

**Comment by ibeltagy** [comment]
You mean difference between this repo and the code in this [PR](https://github.com/huggingface/transformers/pull/4352)? Other than that, they should be the same. 
However, release 2.9.1 doesn't include this PR yet. Hopefully, it will be included in another release some time next week.

**Comment by ibeltagy** [comment]
Longformer was released with HF transformers v2.11.0. I will close this issue for now but please feel free to reopen or create a new one if you have more questions.
