### ISSUE TITLE
Self Attention forward function API is not compatible with current version of transformers

### ISSUE THREAD

**Issue by successar** [allenai/longformer#4]
The current version of transformers library (release 2.8.0) has two more arguments in self attention layer's forward function (https://github.com/huggingface/transformers/blob/500aa12318ce5acd289d5edb6cb8266b3c3b162e/src/transformers/modeling_bert.py#L208). These are not present in longformer self attention forward function.

**Comment by pchankh** [comment]
Any plans to fix/update this longformer compatibility with the latest version of transformers (>=2.8.0) as most will move forward with later transformers version? Thanks.

**Comment by ibeltagy** [comment]
yes, there's a PR for it. We will fix this soon.

**Comment by ibeltagy** [comment]
https://github.com/allenai/longformer/releases/tag/v0.2
