### ISSUE TITLE
CUDA out of memory error for attention mask 2 at cls ids

### ISSUE THREAD

**Issue by anantiitml** [allenai/longformer#41]
Hi,

With batch size 1 whenever i set attention mask to 2 for cls_ids it gives out of memory error else working fine with attention mask set as all ones

**Comment by ibeltagy** [comment]
Can you please provide more details, how big is your gpu memory? How much memory is used without global attention? What is the sequence length? What is the task? Are you using fp16?

**Comment by anantiitml** [comment]
GeForce GTX 1080  11178MiB
without global attention around 7500MB
with global attention shoot up to 11103 MB and then fails at seq length at 3400.

Task classification and tagging joint model 

Dont know about fp16 ? is this something different than gpu i am only using gpu code in pytorch

**Comment by ibeltagy** [comment]
12gb gpu is small and an oom is not surprising in this case. 

I would suggest you try fp16 (16bit floating point precision). IMO, the easiest way to do so as of right now (should get easier with native support in pytorch 1.6.0) is to use `pytorch-lightning` and set the flags `amp_level='O2', precision=16`  (use `O2`, not `O1` as we do [here](https://github.com/allenai/longformer/blob/master/scripts/triviaqa.py#L691)).  You will also need to install [apex](https://github.com/NVIDIA/apex/). Check more instructions [here](https://pytorch-lightning.readthedocs.io/en/0.7.6/apex.html). 

Another relatively easy solution is to use gradient checkpointing. This requires changing [this line](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_bert.py#L406) to 
```
layer_outputs = torch.utils.checkpoint.checkpoint(
                layer_module, hidden_states, attention_mask, head_mask[I],
                encoder_hidden_states, encoder_attention_mask
)  # might break because of weird `args` and `kwargs` issues but you get the general idea
``` 
This can also be a nice addition to the `huggingface/transformers` repo if you want to add it.

**Comment by riklopfer** [comment]
In the paper you report using a batch size of 32 for text classification. How much GPU memory was needed for this? Any tricks like gradient checkpointing?

**Comment by armancohan** [comment]
Effective batch size is 32. We set batch size to 1 and accumulated
gradients.

**Comment by ibeltagy** [comment]
> gradient checkpointing

@riklopfer, just because you mentioned it, gradient checkpionting has been merged into HF/transformers/master. You can now do something like
```
model = AutoModel.from_pretrained("allenai/longformer-base-4096", gradient_checkpointing=True)
```

**Comment by ibeltagy** [comment]
Closing. Please feel free to reopen or create a new one if you have more questions.
