### ISSUE TITLE
tvm doesn't work with cuda version 10.1

### ISSUE THREAD

**Issue by leslyarun** [allenai/longformer#44]
Currently, tvm works only with cuda 10.0. Can we have support for cuda 10.1 and 10.2 as well.

```
OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory
```

**Comment by ibeltagy** [comment]
If you don't care about dilation, I would suggest you just use the `sliding_chunks` implementation which doesn't require the custom cuda kernel. 

If you have to use the tvm kernel because you need dilation, do mind giving the instructions in the `cheatsheet.txt` a shot and recompile the binaries?

**Comment by leslyarun** [comment]
Yes, using sliding_chunks as an alternative
