### ISSUE TITLE
Does LongFormer work with bidirectional context?

### ISSUE THREAD

**Issue by vr25** [allenai/longformer#45]
Hi,

It is mentioned in the paper here "While such models have been successful in autoregressive language modeling, they are unsuitable for transfer learning approaches with tasks that benefit from **bidirectional context**." about the bidirectional context but I just wanted to confirm it.

Thanks!

**Comment by ibeltagy** [comment]
Yes, it does. Each token attends to w/2 tokens before and w/2 tokens after.

**Comment by vr25** [comment]
Thanks a lot!
