### ISSUE TITLE
How can I train the pre-train model on chinese corpus?

### ISSUE THREAD

**Issue by liangxg787** [allenai/longformer#47]
Now I want to train a pre-train model on chinese corpus, but the details are not clear. such as, how to make the minimal changes necessary to support Longformer’s attention mechanism, how to take the attention pattern to plug into a pretrained transformer model.

**Comment by ibeltagy** [comment]
We are working on some script that should make this easy.

**Comment by liangxg787** [comment]
@ibeltagy OK，when will you finish this work and publish the pre-train model based Chinese corpus?

**Comment by ibeltagy** [comment]
We are not going to release a pretrained Chinese model. This is just a script to make it easy to train your own model on your own corpus.

It is a pretty easy procedure. Please check the other issues that asked the same question where we tried to explain the procedure in more detail.

**Comment by liangxg787** [comment]
> We are not going to release a pretrained Chinese model. This is just a script to make it easy to train your own model on your own corpus.
> 
> It is a pretty easy procedure. Please check the other issues that asked the same question where we tried to explain the procedure in more detail.

Thank you very much for releasing the script. I will try to train a pretrained model based Chinese copus after that.
Now I'm trying to use LongformerSelfAttention to replace the encoder in transformer, then build a new model without pretrained model.

**Comment by ibeltagy** [comment]
This notebook replicates our procedure for pretrianing Longformer https://github.com/allenai/longformer/blob/master/scripts/convert_model_to_long.ipynb. It can be applied to other pretrained models to get a version that supports long inputs.

**Comment by liangxg787** [comment]
@ibeltagy Thank you very much. I will try it now。

**Comment by ibeltagy** [comment]
Closing. Please feel free to reopen or create a new one if you have more questions.

**Comment by thesby** [comment]
@liangxg787 Hi, have you trained a Chinese model? Could you please release your model?

**Comment by yysirs** [comment]
@thesby now , huggingface have release chinese pretrain model  
https://huggingface.co/models?search=longformer
