### ISSUE TITLE
How to finetune LongFormer for downstream task on very long documents?

### ISSUE THREAD

**Issue by vr25** [allenai/longformer#49]
Hi,

With respect to my previous issue posted [here](https://github.com/allenai/longformer/issues/48), I wanted to know more about finetuning LongFormer for the downstream task (say, document classification/ regression) on very long documents.

Thank you!

**Comment by ibeltagy** [comment]
I would suggest you check the classification examples in the huggingface/transformers repo.

**Comment by vr25** [comment]
Thank you.
