### ISSUE TITLE
Configuration for RoBERTa

### ISSUE THREAD

**Issue by YeDeming** [allenai/longformer#58]
Great paper, and really clean and explainable repo, Thanks!

In the paper,  you run the sequence length through  the model, collect the output activations and repeat until the context is exhausted. 

What is the max_doc_len and doc_stride for the roberta-base on Wikihop and TriviaQA?

Best,
Deming Ye

**Comment by ibeltagy** [comment]
For TriviaQA, we only use the first 4096 tokens
For Wikihop, we use the whole context (`max_doc_len=inf`) and `doc_stride=0`

**Comment by YeDeming** [comment]
Thanks!
