### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by th00masml** [allenai/longformer#59]
Hi,
I can't run the main script with huggingface model:

longformer-base-4096/

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-8-f8e4eead2388> in <module>
      4 from transformers import RobertaTokenizer
      5 
----> 6 config = LongformerConfig.from_pretrained('longformer-base-4096/')
      7 # choose the attention mode 'n2', 'tvm' or 'sliding_chunks'
      8 # 'n2': for regular n2 attantion

D:\Anaconda3\envs\tf-gpu\lib\site-packages\transformers\configuration_utils.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    161 
    162         # Load config
--> 163         config = cls.from_json_file(resolved_config_file)
    164 
    165         if hasattr(config, 'pruned_heads'):

D:\Anaconda3\envs\tf-gpu\lib\site-packages\transformers\configuration_utils.py in from_json_file(cls, json_file)
    194         with open(json_file, "r", encoding='utf-8') as reader:
    195             text = reader.read()
--> 196         return cls.from_dict(json.loads(text))
    197 
    198     def __eq__(self, other):

D:\Anaconda3\envs\tf-gpu\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    346             parse_int is None and parse_float is None and
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:
    350         cls = JSONDecoder

D:\Anaconda3\envs\tf-gpu\lib\json\decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

D:\Anaconda3\envs\tf-gpu\lib\json\decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

What could be the possible issue?

**Comment by th00masml** [comment]
> In this line `config = LongformerConfig.from_pretrained('longformer-base-4096/')`, are you sure `'longformer-base-4096/'` is a path to a copy of the pretrained model saved on your local disk?

Yes, but I guess there may be something wrong with JSON itself or maybe my copy:

OSError: Couldn't reach server at 'https://s3.amazonaws.com/models.huggingface.co/bert/longformer-base-4096//config.json' to download configuration file or configuration file is not a valid JSON file. Please check network or file content here: C:\Users\bnawa/.cache\torch\transformers\7d5aa25f9de3b640eb94c8d8cf807ac3bfa8a31a18f333071bd61799859a6d7e.

**Comment by ibeltagy** [comment]
`from_pretrained` is treating `longformer-base-4096/` as the name of the model not a path to a directory in your local disk. Try to debug `from_pretrained` and see why this is happening.

If you want to download it from the HF models repo instead, the model name is `"allenai/longformer-base-4096"` (check [here](https://huggingface.co/allenai/longformer-base-4096)).

**Comment by th00masml** [comment]
Debuging is not solving this, but the model is working with HF repo. Thanks
