### ISSUE TITLE
Has anyone reproduced TriviaQA result with pytorch-lightning checkpoint?

### ISSUE THREAD

**Issue by YJYJLee** [allenai/longformer#60]
Hi, I'm trying to reproduce the TriviaQA result following instructions in cheatsheet.
I user following instructions to reproduce it from cheatsheet.txt

// To run our pretrained TriviaQA large model (replicates the leaderboard results),
// first download the pytorch-lightning checkpoint:
// https://ai2-s2-research.s3-us-west-2.amazonaws.com/longformer/triviaqa-longformer-large.tar.gz
// then run:
**python -m scripts.triviaqa  \
    --train_dataset squad-wikipedia-train-4096.json  \  # loaded but not used
    --dev_dataset squad-wikipedia-dev-4096.json  \
    --gpus 0  --num_workers 4 \
    --max_seq_len 4096 --doc_stride -1  \
    --save_prefix triviaqa-longformer-large  \  # pretrained pytorch-lighting checkpoint
    --model_path path/to/pretrained/longformer-large-4096  \  # loaded but not used
    --test   # predictions will be saved into `predictions.json`**

//then run the official evaluation scripts
**python -m scripts.triviaqa_utils.evaluation_utils  \
    --dataset_file path/to/qa/wikipedia-dev.json   \
    --prediction_file predictions.json**
//Output should be:
**{'exact_match': 73.07644188665083, 'f1': 77.78523804802242, 'common': 7993, 'denominator': 7993, 'pred_len': 7993, 'gold_len': 7993}**

But I keep getting result {'exact_match': 0.025021894157387713, 'f1': 4.579085300341775, 'common': 7993, 'denominator': 7993, 'pred_len': 7993, 'gold_len': 7993}, which is very weird..

I downloaded dataset and converted both train and dev dataset into squad format by provided script, and I just replaced data and model path to my server's setting. 

Has anyone reproduced the result f1:77.78 with given pytorch-lightning checkpoint?

**Comment by ibeltagy** [comment]
https://github.com/allenai/longformer/issues/19

**Comment by amyxie361** [comment]
Hi, I get the same result. Have you figured out the bug?

> {'exact_match': 0.025021894157387713, 'f1': 4.548395690911252, 'common': 7993, 'denominator': 7993, 'pred_len': 7993, 'gold_len': 7993}

**Comment by roastduck** [comment]
Same here. I found that the `--save_dir` argument is not the current working directory by default, and tried to directly pass the checkpoint files to the `ModelCheckpoint` object in `scripts/triviaqa.py`, but still not working.

**Comment by roastduck** [comment]
I have finally figured it out. The version of `pytorch-lightning` and `test-tube` should be exact the same with the one specified in `requirements.txt`. Then the model will be correctly loaded.

**Comment by ibeltagy** [comment]
@roastduck, right. Newer versions of PTL doesn't load the checkpoint from the argument specified in `--save_dir`. A PR updating to a newer PTL version and changing the script accordingly will be truly appreciated.

**Comment by YJYJLee** [comment]
@roastduck Glad you figured it out:) Closing issue now.

**Comment by songwanguw** [comment]
@roastduck Do you have script that works for newer PTL?

**Comment by roastduck** [comment]
> @roastduck Do you have script that works for newer PTL?

Unfortunately, no.
