### ISSUE TITLE
Multiple language support

### ISSUE THREAD

**Issue by loretoparisi** [allenai/longformer#64]
Any plan to provide a multi-lingual model?

**Comment by ibeltagy** [comment]
Not really, but you can follow [this notebook](https://github.com/allenai/longformer/blob/master/scripts/convert_model_to_long.ipynb) to convert an existing multilingual model into a long model. [Others](https://github.com/allenai/longformer/issues/54#issuecomment-643134619) have used it with success.

**Comment by loretoparisi** [comment]
Thanks a lot, will try the conversion script then.

**Comment by slvcsl** [comment]
> Not really, but you can follow [this notebook](https://github.com/allenai/longformer/blob/master/scripts/convert_model_to_long.ipynb) to convert an existing multilingual model into a long model. [Others](https://github.com/allenai/longformer/issues/54#issuecomment-643134619) have used it with success.

Hi @ibeltagy, is the notebook still supposed to work? 

I am trying to run it, but I get:

AttributeError                            Traceback (most recent call last)
<ipython-input-22-2426b19e30d3> in <module>()
      5 logger.info(f'Converting roberta-base into roberta-base-{model_args.max_pos}')
      6 model, tokenizer = create_long_model(
----> 7     save_model_to=model_path, attention_window=model_args.attention_window, max_pos=model_args.max_pos)

<ipython-input-17-42fe02ff2bb6> in create_long_model(save_model_to, attention_window, max_pos)
     20         k += step
     21     model.roberta.embeddings.position_embeddings.weight.data = new_pos_embed
---> 22     model.roberta.embeddings.position_ids.data = torch.tensor([i for i in range(max_pos)]).reshape(1, max_pos)
     23 
     24     # replace the `modeling_bert.BertSelfAttention` object with `LongformerSelfAttention`

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
   1129                 return modules[name]
   1130         raise AttributeError("'{}' object has no attribute '{}'".format(
-> 1131             type(self).__name__, name))
   1132 
   1133     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

**AttributeError: 'RobertaEmbeddings' object has no attribute 'position_ids'**

Any help?

**Comment by mzhadigerov** [comment]
@slvcsl  any updates on that?
