### ISSUE TITLE
suddenly missing LongformerForSequenceClassification on huggingface?

### ISSUE THREAD

**Issue by vr25** [allenai/longformer#70]
https://huggingface.co/transformers/model_doc/longformer.html

**Comment by ibeltagy** [comment]
Looks like the documentation was missing in v2.11.0 release but was added in master ([here](https://github.com/huggingface/transformers/commit/37be3786cf1de9d21233f543c231866e68954998#diff-3909947f36862a1731195bf05c85c64cR79)). Looks like the documentation is reading from the last release right now. 

Anyways, you can find the documentation in the class docstring [here](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_longformer.py#L823)

**Comment by ibeltagy** [comment]
Closing. Please feel free to reopen or create a new one if you have more questions.
