### ISSUE TITLE
I  don't understand this part of code in diagonaled_mm_tvm.py 

### ISSUE THREAD

**Issue by SYF111** [allenai/longformer#76]
algorithm = lambda l, i, q, j: tvm.sum(
            tvm.if_then_else(
                t3d3 == m,  # if output dimension == m, then t1 is diagonaled (FIXME: This breaks if t3d3 == m == t1d3)
                tvm.if_then_else(
                    transpose_t1 == 0,
                    tvm.if_then_else(
                        tvm.all(
                            i + D[q] * (k - w) >= 0,
                            i + D[q] * (k - w) < n,
                        ),
                        X[l, i, q, k] * Y[l, i + D[q] * (k - w), q, j],  # t1 is diagonaled
                        padding
                    ),
                    tvm.if_then_else(
                        tvm.all(
                            i + D[q] * (k - w_upper) >= 0,  # `w_upper` to handle the case `autoregressive=True`
                            i + D[q] * (k - w_upper) < n,
                        ),
                        X[l, i + D[q] * (k - w_upper), q, (w_upper + w) - k] * Y[l, i + D[q] * (k - w_upper), q, j],  # # t1 is diagonaled and should be transposed
                        padding
                    ),
                ),
                tvm.if_then_else(
                    tvm.all(
                        i + D[q] * (j - w) >= 0,
                        i + D[q] * (j - w) < n,
                    ),
                    X[l, i, q, k] * Y[l, i + D[q] * (j - w), q, k],  # t1 is not diagonaled, but the output tensor is going to be
                    padding
                )
            ), axis=k)

I got confused by the code above. especially  X[l, i, q, k] * Y[l, i + D[q] * (j - w), q, k]
should't this be a matmul operation ?  but the last two dimension of Y is not transposed.  
I only know the basic of TVM,is this some kind of  trick in here ?

**Comment by ibeltagy** [comment]
This is TVM syntax to describe the computation of the kernel, which TVM compiles to c++. 

> `X[l, i, q, k] * Y[l, i + D[q] * (j - w), q, k],`

Good question. Let's simplify this by removing the batch dimension and the heads dimension, and assume dilation = 1, we get
```
Z[i, j] = X[i, k] * Y[i + (j - w), k]
```
The dimension of these tensors are: 
X: seqlen * hidden_size
Y: seqlen * hidden_size
Z: seqlen * (2w+1) where each column is a "diagonal" of the result matrix if you where to do `matmul(X, Y)`. Basically, each column of Z is a diagonal of the attention matrix (this figure in the paper 
![image](https://user-images.githubusercontent.com/2287797/86040306-a638f500-b9f8-11ea-90c8-52bbe7ea46e6.png) )

This is how we save memory; we don't store the full `matmul(X, Y)`. Instead, we only compute and store its diagonals.

**Comment by SYF111** [comment]
Thanks so much for the answer. I think i figure it out. You guys are doing a great job on this model, learned a lot.
