### ISSUE TITLE
Long Version of ELECTRA_large for Question Answering?

### ISSUE THREAD

**Issue by ahotrod** [allenai/longformer#77]
I have found the SQuAD2.0 performance, compute efficiency, and short inferencing times of ELECTRA-large to be most attractive for my QA applications.  Having reviewed your notebook `convert_model_to_long.ipynb` for creating RobertaLongForMaskedLM, I'm wondering if there are any difficulties/drawbacks/gotchas you may be aware of in converting ELECTRA_large for question answering, i.e. ElectraLongForQuestionAnswering?  Think it's do-able on a single 24GB Titan RTX GPU or would it require GCP TPU(s)?

**Comment by ibeltagy** [comment]
It should be straightforward to the notebook to build `ElectraLongForQuestionAnswering`. 24GB is probably enough for the large model, but even if it is not enough, I would suggest you use `gradient_checkpointing` which will reduce memory usage by close to 5x. To use it, try something like 
```
model = AutoModel.from_pretrained("allenai/longformer-base-4096", gradient_checkpointing=True)
``` 
Make sure to use transformers v3.0.0

**Comment by ibeltagy** [comment]
Closing. Feel free to reopen if needed.

**Comment by aliebi** [comment]
> I have found the SQuAD2.0 performance, compute efficiency, and short inferencing times of ELECTRA-large to be most attractive for my QA applications. Having reviewed your notebook `convert_model_to_long.ipynb` for creating RobertaLongForMaskedLM, I'm wondering if there are any difficulties/drawbacks/gotchas you may be aware of in converting ELECTRA_large for question answering, i.e. ElectraLongForQuestionAnswering? Think it's do-able on a single 24GB Titan RTX GPU or would it require GCP TPU(s)?

Hi, did you train Longformer on Electra?
