### ISSUE TITLE
What special tokens are added to the tokenizer?

### ISSUE THREAD

**Issue by talkhaldi** [allenai/longformer#78]
Hi,

Thank you for your great work!

In page 13 of your paper, where you explain the input format for HotpotQA, you say:

> We particularly use the following input format with special tokens: “[CLS] [q] question [/q] [p] sent1,1 [s] sent1,2 [s] ... [p] sent2,1 [s] sent2,2 [s] ...” where [s] and [p] are special tokens representing sentences and paragraphs. The special tokens were added to the RoBERTa vocabulary and randomly initialized before task finetuning."

Do you use [CLS] as a new added special token or did you actually mean roberta.cls_token (which is "\<s>")? Also, do you use \</s> (equivalent to [SEP]) anywhere? at least at the end of the whole sequence? You don't seem to use it after the question as usually done in other work ("[CLS]Question[SEP]Context[SEP]").

Other than "[CLS]", so you only add the following as additional_special_tokens: ["[q]", "[/q]", "[p]", "[s]"] ?

Thanks in advance!

**Comment by armancohan** [comment]
By `[CLS]` we mean `tokenizer.cls_token` which would be `<s>` token in Roberta tokenizer.
We use `</s>` at the end of the string; and yes, we don't use it after question.

Here are all the additional tokens we ended up using in the final model:
```
QUESTION_START = '[question]'
QUESTION_END = '[/question]' 
TITLE_START = '<t>'  # indicating the start of the title of a paragraph (also used for loss over paragraphs)
TITLE_END = '</t>'   # indicating the end of the title of a paragraph
SENT_MARKER_END = '[/sent]'  # indicating the end of the title of a sentence (used for loss over sentences)
PAR = '[/par]'  # used for indicating end of the regular context and beginning of `yes/no/null` answers
```
The format of the context is this:
```
<s> [question] q q q [/question] <t> title 1 </t> s_11 s_12 s_13 [/sent] s_21 s_22 s_23 [/sent] ... <t> title 2 </t> s_21 s_22 s_23 [/sent] .... [/par] yes no null </s>
```
where `q`s are question tokens, `s_ij` is the `j`th token in sentence `i` in the paragraph.

**Comment by talkhaldi** [comment]
Got it. Thanks for the clear explanation!

**Comment by talkhaldi** [comment]
One follow up question, is there a reason why you didn't use </s> after the question? Did it perform better without it?
