### ISSUE TITLE
Fine-tuning Longformer for squad (out of memory) 

### ISSUE THREAD

**Issue by arashashari** [allenai/longformer#81]
I have pretrained an MLM Longformer using roberta-base based on [this recipe](https://github.com/allenai/longformer/blob/master/scripts/convert_model_to_long.ipynb). 

Then I tried to fine-tune it for squad quetion-answering. Here is the [trainer](https://github.com/huggingface/transformers/blob/master/examples/question-answering/run_squad.py) and following is the run-time setting (based on [here](https://github.com/huggingface/transformers/tree/master/examples/question-answering)):

python run_squad.py \
  --model_type roberta \
  --model_name_or_path pathe_to_roberta_base_mlm_trained_4096 \
  --do_train \
  --do_eval \
  --do_lower_case \
  --train_file $SQUAD_DIR/train-v1.1.json \
  --predict_file $SQUAD_DIR/dev-v1.1.json \
  --per_gpu_train_batch_size 1 \
  --learning_rate 3e-5 \
  --num_train_epochs 2.0 \
  --max_seq_length 4096 \
  --doc_stride 128 \
  --output_dir /tmp/debug_squad/

While I am using a V100 node (16-GPUs, 32 GB), it always faces memory limit of gpu as follow:

    File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/aaaa/.local/lib/python3.6/site-packages/transformers/modeling_roberta.py", line 642, in forward
    output_hidden_states=output_hidden_states,
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/aaaa/.local/lib/python3.6/site-packages/transformers/modeling_bert.py", line 762, in forward
    output_hidden_states=output_hidden_states,
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/aaaa/.local/lib/python3.6/site-packages/transformers/modeling_bert.py", line 439, in forward
    output_attentions,
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/aaaa/.local/lib/python3.6/site-packages/transformers/modeling_bert.py", line 371, in forward
    hidden_states, attention_mask, head_mask, output_attentions=output_attentions,
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/aaaa/.local/lib/python3.6/site-packages/transformers/modeling_bert.py", line 315, in forward
    hidden_states, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask, output_attentions,
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/aaaa/.local/lib/python3.6/site-packages/transformers/modeling_bert.py", line 240, in forward
    attention_scores = attention_scores / math.sqrt(self.attention_head_size)
RuntimeError: CUDA out of memory. Tried to allocate 768.00 MiB (GPU 0; 31.72 GiB total capacity; 30.25 GiB already allocated; 300.38 MiB free; 30.29 GiB reserved in total by PyTorch)

However, using [allenai/longformer-base-4096](https://huggingface.co/allenai/longformer-base-4096), it works. Could you please comment on what I may be missing in the above steps.

**Comment by ibeltagy** [comment]
The default batch size is 8 but you probably need a batch size of 1. 
Try `--per_gpu_train_batch_size 1 --gradient_accumulation_steps 8`

**Comment by arashashari** [comment]
Thanks @ibeltagy , that works, however f1/em is very far from what was expected (compared to either of roberta/longformer-base-4096 pre-trained model);   ~8/~1 compared to ~90/~82. I believe there is something wrong in my setting but not sure what. I just followed the exact same steps as described above. I wonder if you can comment on this.
Is there any tutorial for how to use Longformer for question-answering starting from a bert/roberta checkpoint?

**Comment by arashashari** [comment]
Here is the config from the pre-trained MLM I am using:
{
  "architectures": [
    "RobertaLongForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "attention_window": [
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512,
    512
  ],
  "bos_token_id": 0,
  "eos_token_id": 2,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 4098,
  "model_type": "roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "type_vocab_size": 1,
  "vocab_size": 50265
}

**Comment by ibeltagy** [comment]
What is `RobertaLongForMaskedLM`? is this a model you created? 

To narrow down the search space, can you try your training with regular RoBERTa and with Longformer first. If they work, then it is a problem with `RobertaLongForMaskedLM`

**Comment by arashashari** [comment]
It is the model I pre-trained based on the suggested [notebook](https://github.com/allenai/longformer/blob/master/scripts/convert_model_to_long.ipynb).

Yes, I have already tested RoBERTa and Longformer and those works correctly; the correct number above are from those.

**Comment by ibeltagy** [comment]
so either something wrong with the model weights or the `run_squad.py` script is not compatible with the model implementation for some reason. It is probably the second but just to make sure, can you load the model then use the `pretrain_and_evaluate` function in the notebook and evaluate it on wikitext103 see what `bpc` numbers you get. Also, check if it is the same `bpc` number you got before `model.save_pretrained(model_path)`

**Comment by arashashari** [comment]
Thanks @ibeltagy, have same feeling as your second point. I am running run_squad.py combining it with the notebook; fine-tune from RoBERTa checkpoint. Doing it for 4 epochs and see what will happend.
I will test your suggestion as well and will update you.

**Comment by arashashari** [comment]
After fine-tuning from RoBERTa it works fine.
