### ISSUE TITLE
Train a longformer with pretrain bert?

### ISSUE THREAD

**Issue by RyanHuangNLP** [allenai/longformer#82]
Is it just need to replace the RobertaForMaskedLM, RobertaTokenizerFast to the bert one?

**Comment by ibeltagy** [comment]
You can follow this notebook to train a long version of BERT.

**Comment by RyanHuangNLP** [comment]
@ibeltagy Thanks for response. I have already run the notebook, I want to make sure that replace the RobertaForMaskedLM, RobertaTokenizerFast to the Bert one can train a bert pretrain longformer

**Comment by ibeltagy** [comment]
yes, but you need to review the notebook carefully because it has details that are specific to RoBERTa. For example, the position embeddings of BERT are not under `model.roberta.embeddings.position_embeddings`, and BERT doesn't reserve the first two positions for padding tokens.

**Comment by RyanHuangNLP** [comment]
@ibeltagy Is there any bugs in the notebook, `ValueError: Some specified arguments are not used by the HfArgumentParser: ['--device', 'cuda0']`? And did you test the notebook can train with 2GB corpus without CUDA OOM?

**Comment by ibeltagy** [comment]
glad you figured it out. There's a change in the recent release that cause this issue.

**Comment by ibeltagy** [comment]
Updated the notebook to support transformers==3.0.1
