### ISSUE TITLE
unexpected keyword argument 'output_attentions' in `convert_model_to_long.ipynb`

### ISSUE THREAD

**Issue by PhilipMay** [allenai/longformer#87]
Cell 3 in `convert_model_to_long.ipynb` calls `__init__` of  `LongformerSelfAttention` with the argument called `output_attentions`. This argument does not exist. So this is thrown: `TypeError: forward() got an unexpected keyword argument 'output_attentions'`

**Comment by PhilipMay** [comment]
nm - did not see the .forward call

**Comment by thesby** [comment]
How to solve this problem?

**Comment by thesby** [comment]
```
def forward(
        self, hidden_states, attention_mask=None, is_index_masked=None, is_index_global_attn=None, is_global_attn=None
    ):
```
there is not output_attentions in `forward`
