### ISSUE TITLE
Pretraining Dataset Details

### ISSUE THREAD

**Issue by sjy1203** [allenai/longformer#90]
Hello,

In the paper, it said 
> We additionally included one third of a subset of the Realnews dataset (Zellers et al., 2019) with documents longer than 1,200 tokens as well as one third of the Stories (Trinh and Le, 2018) corpus.

Does it mean the Stories Corpus was also preprocessed by excluding documents less than 1,200 tokens? 

Could you kindly provide the link to download the preprocessed Stories corpus or scripts? I want to use the same pretraining datasets below for my own model to make fair comparison with longformer.

![image](https://user-images.githubusercontent.com/6142174/88768746-15e40080-d1ae-11ea-894d-516e87d6ffb7.png)

**Comment by armancohan** [comment]
We did not perform length filtering on the Stories corpus (most documents in this corpus are large).
We may not be able to release the data ourselves but the corpus is publicly available by the original authors (Trinh and Le, 2018). To have a comparable corpora you can download the corpus and randomly sample one third of it. 
For preprocessing we used RoBERTa's scripts: https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.pretraining.md

**Comment by sjy1203** [comment]
Thanks, I'll have a try. :)

**Comment by ibeltagy** [comment]
Closing. Please feel free to reopen if needed.
