### ISSUE TITLE
Does transformers use the custom CUDA kernel?

### ISSUE THREAD

**Issue by Maybewuss** [allenai/longformer#92]

**Comment by ibeltagy** [comment]
You mean the huggingface implememtation? No

**Comment by Maybewuss** [comment]
> You mean the huggingface implementation? No

So the time complexity is still O(n^2) ?
Why not use global attention for all tokens if the time complexity is not falling ？

**Comment by ibeltagy** [comment]
> So the time complexity is still O(n^2) ?

The HF implementation is using our `sliding_chunks` implementation of the sliding window attention (check readme for details), and its time/memory complexity if O(n). 

> Why not use global attention for all tokens if the time complexity is not falling ？

Global attention for all tokens is equivalent to full O(n^2) attention which is still problematic.

**Comment by Maybewuss** [comment]
> > So the time complexity is still O(n^2) ?
> 
> The HF implementation is using our `sliding_chunks` implementation of the sliding window attention (check readme for details), and its time/memory complexity if O(n).
> 
> > Why not use global attention for all tokens if the time complexity is not falling ？
> 
> Global attention for all tokens is equivalent to full O(n^2) attention which is still problematic.

Thanks~

**Comment by ibeltagy** [comment]
Closing. Please feel free to reopen if needed.
