### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered - is_global_attn = is_index_global_attn.flatten().any().item()

### ISSUE THREAD

**Issue by zarandioon** [allenai/longformer#99]
I'm trying to train a new model from scratch where it's length is 1024 (using huggingface implementation of longformer), but I get the following exception at a line that is recently added:

```
--> 150         is_global_attn = is_index_global_attn.flatten().any().item()
    151 
    152         hidden_states = hidden_states.transpose(0, 1)

RuntimeError: CUDA error: device-side assert triggered
```

I tried Reformer and it worked as expected. The Longfomer config is as follows?

```
LongformerConfig {
  "attention_probs_dropout_prob": 0.1,
  "attention_window": 64,
  "bos_token_id": 0,
  "eos_token_id": 2,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 1026,
  "model_type": "longformer",
  "num_attention_heads": 12,
  "num_hidden_layers": 6,
  "pad_token_id": 257,
  "sep_token_id": 258,
  "type_vocab_size": 2,
  "vocab_size": 261
}
```

Any idea what the issue is?

**Comment by ibeltagy** [comment]
This line is unlikely to be the reason for the error. Try `export CUDA_LAUNCH_BLOCKING=1` to disable asynchronous cuda execution, then run your code again. This will point you to the actual line that's causing the problem.

**Comment by zarandioon** [comment]
In RoBERTa model, for some reasons (potentially for backwards compatibility reasons), the pad ids is added to the position id. For this case, I was using a PAD ID that was not zero, and this was causing the ids to go beyond the embedding index limit and that was causing this issue.  Thanks ibeltagy@ for your help on this.

https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_roberta.py#L804

**Comment by ibeltagy** [comment]
Glad you figured it out.
